"""
Constants used throughout the DeepLiveCam application.
Centralizes magic numbers and configuration values for easier maintenance.
"""

# Face Detection
FACE_DETECTION_SIZE = (640, 640)
FACE_DETECTION_CTX_ID = 0
FACE_CONFIDENCE_THRESHOLD = 0.5

# Face Rotation Angles (for improved detection)
ROTATION_ANGLES_COARSE = [0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180,
                          -15, -30, -45, -60, -75, -90, -105, -120, -135, -150, -165, -180]
ROTATION_ANGLES_FINE = [12.5, 10, 7.5, 5, 2.5, -2.5, -5, -7.5, -10, -12.5]

# UI Dimensions
UI_ROOT_WIDTH = 600
UI_ROOT_HEIGHT = 700

UI_PREVIEW_MAX_WIDTH = 1200
UI_PREVIEW_MAX_HEIGHT = 700
UI_PREVIEW_DEFAULT_WIDTH = 960
UI_PREVIEW_DEFAULT_HEIGHT = 540

UI_POPUP_WIDTH = 750
UI_POPUP_HEIGHT = 810
UI_POPUP_SCROLL_WIDTH = 740
UI_POPUP_SCROLL_HEIGHT = 700

UI_POPUP_LIVE_WIDTH = 900
UI_POPUP_LIVE_HEIGHT = 820
UI_POPUP_LIVE_SCROLL_WIDTH = 890
UI_POPUP_LIVE_SCROLL_HEIGHT = 700

UI_MAPPER_PREVIEW_MAX_WIDTH = 100
UI_MAPPER_PREVIEW_MAX_HEIGHT = 100

UI_DEFAULT_BUTTON_WIDTH = 200
UI_DEFAULT_BUTTON_HEIGHT = 40

UI_THUMBNAIL_SIZE = (200, 200)

# Video Processing
VIDEO_ENCODING_PRESET = "medium"
VIDEO_AUDIO_CODEC = "aac"
VIDEO_AUDIO_BITRATE = "128k"
VIDEO_PIXEL_FORMAT = "yuv420p"
VIDEO_COLOR_SPACE = "colorspace=bt709:iall=bt601-6-625:fast=1"
VIDEO_DEFAULT_FPS = 30.0
VIDEO_DEFAULT_QUALITY = 18
VIDEO_MAX_QUALITY = 51

# FFmpeg
FFMPEG_LOG_LEVEL = "error"
FFMPEG_FRAME_FORMAT = "%04d.png"

# File System
TEMP_FILE_NAME = "temp.mp4"
TEMP_DIRECTORY_NAME = "temp"
SWITCH_STATES_FILE = "switch_states.json"

# File Types
IMAGE_EXTENSIONS = ('.png', '.jpg', '.jpeg', '.gif', '.bmp')
VIDEO_EXTENSIONS = ('.mp4', '.mkv', '.avi')

# Memory and Performance
DEFAULT_MAX_MEMORY_GB = 16
DEFAULT_MAX_MEMORY_GB_DARWIN = 4
DEFAULT_EXECUTION_THREADS = 8
SINGLE_THREAD_EXECUTION_THREADS = 1

# Model Paths
MODEL_DIRECTORY = "models"
MODEL_FACE_SWAPPER_FP32 = "inswapper_128.onnx"
MODEL_FACE_SWAPPER_FP16 = "inswapper_128_fp16.onnx"
MODEL_FACE_ENHANCER = "GFPGANv1.4.pth"
MODEL_FACE_ANALYSER = "buffalo_l"

# Model URLs
MODEL_URL_FACE_SWAPPER = "https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128_fp16.onnx"
MODEL_URL_FACE_ENHANCER = "https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth"

# Clustering
CLUSTERING_MAX_K = 10
CLUSTERING_MIN_K = 2

# Video Processing
VIDEO_FRAME_SAMPLE_COUNT = 15
VIDEO_FRAME_QUALITY_JPEG = 2

# Camera
CAMERA_DEFAULT_WIDTH = 960
CAMERA_DEFAULT_HEIGHT = 540
CAMERA_DEFAULT_FPS = 60
CAMERA_FPS_UPDATE_INTERVAL = 0.5
CAMERA_MAX_INDEX_SCAN = 10

# Mouth Mask
MOUTH_MASK_DEFAULT_FEATHER_RATIO = 8
MOUTH_MASK_DEFAULT_DOWN_SIZE = 0.50
MOUTH_MASK_DEFAULT_SIZE = 1

# FPS Display
FPS_TEXT_POSITION = (10, 30)
FPS_FONT = 1  # cv2.FONT_HERSHEY_SIMPLEX
FPS_FONT_SCALE = 1
FPS_FONT_COLOR = (0, 255, 0)
FPS_FONT_THICKNESS = 2

# Disk Space Safety
DISK_SPACE_MULTIPLIER = 10  # Safety multiplier for frame size estimation
